import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Header } from "../components/Header";

import { v4 as uuidv4 } from "uuid";

export default function Home() {
  const router = useRouter();

  // useEffect(() => {
  //   async function fetchData() {
  //     const response = await fetch(
  //       "https://www.random.org/integers/?num=4&min=0&max=7&col=1&base=10&format=plain&rnd=new"
  //     );
  //     const text = await response.text();
  //     const integers = text.split("\n").map((intString) => parseInt(intString));
  //     integers.pop();
  //     setCode(integers);
  //   }
  //   fetchData();
  // }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mx-auto w-[500px] flex flex-col space-y-2">
        <button onClick={() => router.push(`/game/${uuidv4()}`)}>start</button>
        <button>join</button>
      </div>
    </>
  );
}
