import Head from "next/head";
import { useEffect, useState } from "react";

import { GameBoard } from "../components/Game";
import { Header } from "../components/Header";
import { Options } from "../components/Options";

export default function Home() {
  const [numbers, setNumbers] = useState<number[]>();

  useEffect(() => {
    async function fetchData() {
      const response = await fetch(
        "https://www.random.org/integers/?num=4&min=1&max=6&col=1&base=10&format=plain&rnd=new"
      );
      const text = await response.text();
      const integers = text.split("\n").map((intString) => parseInt(intString));
      integers.pop();
      setNumbers(integers);
    }
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mx-auto w-[500px] bg-green-500 space-y-4">
        <div className="flex justify-center">
          {numbers ? numbers : "Loading..."}
        </div>
        <GameBoard />
        <Options />
      </div>
    </>
  );
}
